services:
  api:
    build:
      context: ./backend
    env_file:
      - ./backend/.env
    environment:
      - NODE_ENV=production
      - PORT=5000
    ports:
      - "5000:5000"
    healthcheck:
      test:
        ["CMD-SHELL", "node -e \"fetch('http://localhost:5000/api/health').then(res => res.ok ? process.exit(0) : process.exit(1)).catch(() => process.exit(1));\""]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 5s
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    ports:
      - "8080:80"
    depends_on:
      api:
        condition: service_healthy
    restart: unless-stopped

networks:
  default:
    driver: bridge
